### ISSUE TITLE
Support Bazel based repos

### ISSUE THREAD

**Issue by achew22** [renovatebot/renovate#2816]
**What would you like Renovate to be able to do?**

From your documentation:

> Renovate will silently ignore any repositories that don't have a package.json file, however most people choose to select which repositories to include. Unfortunately GitHub doesn't yet offer the chance to "select all but exclude some" so instead you need to select all that you want. The form also requires you to start typing before it suggests to you repositories, which is a bit of a pain.

**Describe the solution you'd like**

Also run if there is a `WORKSPACE` file in the root of the repo.

**Describe alternatives you've considered**

If there is a UI that you could force enrollment through that might also be useful.

**Additional context**

The `WORKSPACE` file is conceptually similar to a `package.json` and is the standard process of defining something as a Bazel repo.

**Comment by rarkins** [comment]
That documentation was long out of date and has been fixed. Renovate will scan for all known package files including `WORKSPACE` files, not just `package.json`.

**Comment by achew22** [comment]
@rarkins thanks so much for addressing that! I'm still having a hard time turning on renovate for `grpc-ecosystem/grpc-gateway` which the bot should have access to. Is there something obvious I'm missing?

**Comment by rarkins** [comment]
@achew22 	the @grpc-ecosystem account is not showing up as installed at all from my end. Can the owner of the org go to https://github.com/apps/renovate and check what they see there?
