### ISSUE TITLE
Lock file problem

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3184]
**What Renovate type are you using?**
Renovate App

**Describe the bug**
I get this in some PRs:
<img width="831" alt="screen shot 2019-02-07 at 18 26 09" src="https://user-images.githubusercontent.com/20856232/52430211-e2b73880-2b05-11e9-9e3e-11859c5fd186.png">

**Did you see anything helpful in debug logs?**
No

I encountered this problem in the following PRs:
https://github.com/dmx-io/dmx-websockets/pull/9
https://github.com/dmx-io/npm-galves/pull/16
https://github.com/dmx-io/winston-loggly/pull/20
https://github.com/dmx-io/npm-winston-slack/pull/15
https://github.com/dmx-io/npm-logger/pull/40
https://github.com/dmx-io/npm-kelley-blue-book/pull/23
https://github.com/dmx-io/npm-black-book/pull/17

I added `npmToken` to `renovate.json` everywhere. In the repos above I saw `Lock file problem` info but in the remaining repos not. However renovate didn't update any of my private libraries in any repo.

**Comment by rarkins** [comment]
How exactly are you configuring? Please show your config but redact your token.

Also, do you have any

**Comment by piotr-s-brainhub** [comment]
`renovate.json`:
```
{
  "commitMessage": "[renovate] update all dependencies",
  "groupName": "All",
  "labels": ["renovate"],
  "npmToken": "<my-token>"
}
```

I have no `.npmrc` file

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I also checked my token is correct:
- I run `npm logout`
- I wasn't able to install my private libraries
- I created `~/.npmrc` with:
```
always-auth=true
//registry.npmjs.org/:_authToken=<my-token>
```
- I was able to install my private libraries

**Comment by rarkins** [comment]
So the token:
- is configured directly for each repo (not in a preset)?
- is unencrypted?

**Comment by rarkins** [comment]
Can you also make sure the “npm install” still works after you have removed the node_modules?

**Comment by piotr-s-brainhub** [comment]
@rarkins 
- each repo (except of `koa-joi-router` and `npm-grade-it-tools` which have also `packageRules ` field) contains exactly the same `renovate.json` with no inheritance
- it's directly pushed with no encryption
- locally it works after removing `node_modules`

**Comment by rarkins** [comment]
@piotr-s-brainhub 	thanks for your help in troubleshooting the issue and sorry for the inconvenience. I tracked down the problem and it is now resolved. npm increased the length of tokens and we had some logic that attempted to guess whether a token was encrypted or non-encrypted based on its length.

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I see now it's fixed and renovate opened some PRs with private libs update. However for most repos it's still not opened (e.g. updating `@dmx/npm-dmx-utils` in `dmx-payments`).
So what is ETA of opening all the PRs in `dmx-io` organization with upgrading private libraries?

**Comment by rarkins** [comment]
@piotr-s-brainhub looking at the logs, it shows you have that dependency as a range: `depName":"@dmx/npm-dmx-utils","currentValue":"^2.3.0"`. Therefore any `2.x` version falls within that range and there is no need to "update" it. This actually has nothing to do with private vs public at all - it's a general topic about ranges.

About dependencies and ranges:
- If you don't need ranges, then don't use them. Pin exact versions for more control
- If you need a range, then it's presumably because you're writing a library that has downstream consumers. In this case you would normally want to keep your range as wide as possible for compatibility reasons

You can read an in-depth article on the topic here: https://renovatebot.com/docs/dependency-pinning/

If your current value is `^2.3.0` and a new value like `2.4.0` is released, what is your expectation? If you want your `package.json` updated to be `^2.4.0` then add `"rangeStrategy": "bump"` to your config.

By the way, it's really easy for me to miss comments on closed issues, so please open a new issue in https://github.com/renovatebot/config-help if you want to discuss more.
