### ISSUE TITLE
"platform-failure" error with repo nested in group on Gitlab

### ISSUE THREAD

**Issue by vlexaargas** [renovatebot/renovate#4117]
**What Renovate type are you using?**
Renovate CLI & Renovate Dashboard

**Describe the bug**
The dashboard does not load any repos.
The CLI command ends successfully but skips the repo I am trying to set up.

**Did you see anything helpful in debug logs?**
```
DEBUG: git clone error (repository=taivara-client-projects/co-name/fmc-web)
       "err": {
         "message": "Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n    at onErrorNT (internal/child_process.js:456:16)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
         "stack": "Error: Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n    at onErrorNT (internal/child_process.js:456:16)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)\n    at /usr/local/share/.config/yarn/global/node_modules/simple-git/promise.js:62:29\n    at Git.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/git.js:222:18)\n    at Function.Git.fail (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/git.js:1484:18)\n    at fail (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/git.js:1442:20)\n    at /usr/local/share/.config/yarn/global/node_modules/simple-git/src/git.js:1451:16"
       }
DEBUG: Caught initRepo error (repository=taivara-client-projects/co-name/fmc-web)
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at Storage.initRepo (/usr/local/share/.config/yarn/global/node_modules/renovate/dist/platform/git/storage.js:90:23)"
       }
 INFO: Unknown GitLab initRepo error (repository=taivara-client-projects/co-name/fmc-web)
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at Storage.initRepo (/usr/local/share/.config/yarn/global/node_modules/renovate/dist/platform/git/storage.js:90:23)"
       }
 INFO: Platform error - skipping (repository=taivara-client-projects/co-name/fmc-web)
 INFO: Finished repository (repository=taivara-client-projects/co-name/fmc-web)
DEBUG: Host request stats (milliseconds)
       "hostStats": {"gitlab.com": {"requests": 3, "sum": 297, "average": 99, "median": 133}}
 INFO: Renovate finished

```

**To Reproduce**

1.  Create repository with that is nested inside a group on Gitlab
2.  Run the `renovate` CLI.

**Expected behavior**
I expect to see the onboarding PR created.

**Comment by rarkins** [comment]
GitLab started throwing a lot of errors within the last hour - it's not specific to your repo. There were no changes on our backend so my assumption is that it will clear on its own, but I'll monitor it to make sure.

**Comment by vlexaargas** [comment]
Okay 👍 thank ya sir! That said, I was seeing this behavior yesterday as well for several hours.

**Comment by rarkins** [comment]
I noticed it in the last hour because we were throwing `platform-error` instead of `platform-failure`. Normally platform-failures are logged but gracefully ignored, but platform-error was unknown so triggered error alerts to me via the app. I pushed a fix for platform-error/platform-failure to the app not long ago, although all that will do is stop me getting non-stop alerts. I'll watch it

**Comment by rarkins** [comment]
Strangely, Docker Hub went down immediately after this (5xx errors for everything) and then GitHub followed too. So it's been error after error and hard to monitor at a meta level. What's the job_id of one of your failures from before?

**Comment by vlexaargas** [comment]
Hi @rarkins. Apologies for the delay on this (have been out of town) but I am still seeing the same errors. Here is job # from today: 260344253. Any insight on what might be going on?

**Comment by toxsick** [comment]
Hey Guys,

I am seing something similar for months now, which keeps me from updating to v19:

```
INFO: Renovating repository (repository=fuf/projectname)
INFO: Initialising git repository into /tmp/renovate/repos/gitlab/fuf/projectname (repository=fuf/projectname)
INFO: Unknown GitLab initRepo error (repository=fuf/projectname)
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at Storage.initRepo (/builds/fuf/renovate/node_modules/renovate/dist/platform/git/storage.js:90:23)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
INFO: Platform error - skipping (repository=fuf/projectname)
```

Every repo failes like that. Strange thing is that it works when I run it on my local machine, but in our Gitlab CI environment this happens with every repo. This starts to happen when I upgrade to renovate higher then v16.

Can I perhaps provide more debug output. Really want to upgrade to latest version!

**Comment by rarkins** [comment]
@toxsick 	if you can run with LOG_LEVEL=debug then it hopefully dumps the raw `err` object.

**Comment by toxsick** [comment]
Sorry @rarkins for the late response. Here is my debug output:

```
yarn run v1.17.3
$ concurrently --restart-tries 3 --restart-after 10000 --raw "yarn renovate:start"
$ RENOVATE_TOKEN=${GITLAB_TOKEN} NODE_EXTRA_CA_CERTS=./misc/_ca.pem renovate --log-level debug --git-author donotreply@xx.xx --platform gitlab --endpoint https://git.xx.xx/api/v4/ $(cat repositories.txt | xargs)
 WARN: RE2 not usable, falling back to RegExp
       "err": {
         "code": "MODULE_NOT_FOUND",
         "message": "Cannot find module 're2'",
         "stack": "Error: Cannot find module 're2'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/builds/xx/xx/node_modules/renovate/dist/util/regex.js:7:17)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)"
       }
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {
         "repositories": [
           "xx/repo",
         ],
         "logLevel": "debug",
         "platform": "gitlab",
         "endpoint": "https://git.xx.xx/api/v4/",
         "gitAuthor": "donotreply@xx.xx"
       }
DEBUG: Env config
       "config": {"hostRules": [], "token": "***********"}
DEBUG: Combined config
       "config": {
         "hostRules": [],
         "token": "***********",
         "repositories": [
           "xx/repo",
         ],
         "logLevel": "debug",
         "platform": "gitlab",
         "endpoint": "https://git.xx.xx/api/v4/",
         "gitAuthor": "donotreply@xx.xx"
       }
 INFO: Using configured gitAuthor (donotreply@xx.xx)
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
 INFO: Renovating repository (repository=xx/repo)
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/xx/repo (repository=xx/repo)
DEBUG: xx/repo default branch = develop (repository=xx/repo)
DEBUG: Bot email=donotreply@xx.xx (repository=xx/repo)
DEBUG: Enabling Git FS (repository=xx/repo)
DEBUG: xx/repo http URL = https://git.xx.xx/xx/repo.git (repository=xx/repo)
 INFO: Initialising git repository into /tmp/renovate/repos/gitlab/xx/repo (repository=xx/repo)
DEBUG: git clone error (repository=xx/repo)
       "err": {
         "message": "Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)",
         "stack": "Error: Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n    at /builds/xx/xx/node_modules/simple-git/promise.js:62:29\n    at Git.<anonymous> (/builds/xx/xx/node_modules/simple-git/src/git.js:214:18)\n    at Function.Git.fail (/builds/xx/xx/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/builds/xx/xx/node_modules/simple-git/src/git.js:1432:20)\n    at /builds/xx/xx/node_modules/simple-git/src/git.js:1441:16"
       }
DEBUG: Caught initRepo error (repository=xx/repo)
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at Storage.initRepo (/builds/xx/xx/node_modules/renovate/dist/platform/git/storage.js:93:23)"
       }
 INFO: Unknown GitLab initRepo error (repository=xx/repo)
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at Storage.initRepo (/builds/xx/xx/node_modules/renovate/dist/platform/git/storage.js:93:23)"
       }
 INFO: Platform error - skipping (repository=xx/repo)
 INFO: Finished repository (repository=xx/repo)
```

Anything suspicious? I am using a self hosted gitlab with self signed certs and renovate is executed inside a `node:lts-alpine` image. Could this be related to SSL?

regards

**Comment by vlexaargas** [comment]
@toxsick Turns out that renovate does not work on alpine docker images. We faced the same exact issue, moved from node:alpine to node:10.16.3 and everything has been great since!

**Comment by toxsick** [comment]
@vlexaargas thanks for your answer. Alpine seems to definitely be a problem here. I switched to `node:lts` image and I also had to add `export GIT_SSL_NO_VERIFY=1` to make it work.

To be honest I don't really understand why, because my repo is cloded into the runner without a problem, but there seems to be some problem in the simple-git dependency:

```
"err": {
    "message": "Cloning into '.'...\nfatal: unable to access 'https://**redacted**@git.xx.xx/xx/repo.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none\n",
    "stack": "Error: Cloning into '.'...\nfatal: unable to access 'https://**redacted**@git.xx.xx/xx/repo.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none\n\n    at /builds/xx/repo/node_modules/simple-git/promise.js:62:29\n    at Git.<anonymous> (/builds/xx/repo/node_modules/simple-git/src/git.js:214:18)\n    at Function.Git.fail (/builds/xx/repo/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/builds/xx/repo/node_modules/simple-git/src/git.js:1432:20)\n    at /builds/xx/repo/node_modules/simple-git/src/git.js:1441:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```

Turning of git ssl verify is not optimal, but I can live with it for now..

**Comment by rarkins** [comment]
Why aren’t you using the “offical” docker image we publish?

**Comment by toxsick** [comment]
@rarkins I think I went down this path, because I also had problems with the self signed certs of our gitlab instance. But good point, I will give it a try again.

**Comment by rarkins** [comment]
Sorry, my reply sounded a bit like a scolding! I think I typed it from mobile and it came out wrong. I was just interested to know if there's any problem with the default images we publish. BTW if you only use npm/yarn/pnpm and Docker then the slim image will be best/smallest.

**Comment by toxsick** [comment]
No offense taken :) I will try the official image and post my findings here for later reference. 

Thanks for this awesome project, helps a lot!
