### ISSUE TITLE
Renovate fails when Gradle search for plugins in Artifactory

### ISSUE THREAD

**Issue by gmariotti** [renovatebot/renovate#5176]
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

For each gradle projects, we define a custom repository in the `settings.gradle.kts` file with username, password and url coming from environment variables. Not sure since which version of renovate, but it seems that when `bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"` is run, the environment variables in the container are no longer passed.

**Did you see anything helpful in debug logs?**

```
WARN: Gradle run failed (repository=shared-services/payment-solutions/marketpay/marketpay-kotlin-plugin)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"",
         "stdout": "Downloading https://services.gradle.org/distributions/gradle-5.6.4-bin.zip\n.........................................................................................\nUnzipping /home/ubuntu/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4-bin.zip to /home/ubuntu/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux\nSet executable permissions for: /home/ubuntu/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4/bin/gradle\n\nWelcome to Gradle 5.6.4!\n\nHere are the highlights of this release:\n - Incremental Groovy compilation\n - Groovy compile avoidance\n - Test fixtures for Java projects\n - Manage plugin versions via settings script\n\nFor more details see https://docs.gradle.org/5.6.4/release-notes.html\n\nStarting a Gradle Daemon (subsequent builds will be faster)\nnull\n",
         "stderr": "\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file '/tmp/renovate/repos/gitlab/shared-services/payment-solutions/marketpay/marketpay-kotlin-plugin/build.gradle.kts' line: 12\n\n* What went wrong:\nPlugin [id: 'com.olx.marketpay.kotlin', version: '0.5.1'] was not found in any of the following sources:\n\n- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)\n- Plugin Repositories (could not resolve plugin artifact 'com.olx.marketpay.kotlin:com.olx.marketpay.kotlin.gradle.plugin:0.5.1')\n  Searched in the following repositories:\n    maven(https://artifactory.olx.berlin/artifactory/shared-services-maven)\n    Gradle Central Plugin Repository\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 34s\n",
         "message": "Command failed: bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file '/tmp/renovate/repos/gitlab/shared-services/payment-solutions/marketpay/marketpay-kotlin-plugin/build.gradle.kts' line: 12\n\n* What went wrong:\nPlugin [id: 'com.olx.marketpay.kotlin', version: '0.5.1'] was not found in any of the following sources:\n\n- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)\n- Plugin Repositories (could not resolve plugin artifact 'com.olx.marketpay.kotlin:com.olx.marketpay.kotlin.gradle.plugin:0.5.1')\n  Searched in the following repositories:\n    maven(https://artifactory.olx.berlin/artifactory/shared-services-maven)\n    Gradle Central Plugin Repository\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 34s\n",
         "stack": "Error: Command failed: bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file '/tmp/renovate/repos/gitlab/shared-services/payment-solutions/marketpay/marketpay-kotlin-plugin/build.gradle.kts' line: 12\n\n* What went wrong:\nPlugin [id: 'com.olx.marketpay.kotlin', version: '0.5.1'] was not found in any of the following sources:\n\n- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)\n- Plugin Repositories (could not resolve plugin artifact 'com.olx.marketpay.kotlin:com.olx.marketpay.kotlin.gradle.plugin:0.5.1')\n  Searched in the following repositories:\n    maven(https://artifactory.olx.berlin/artifactory/shared-services-maven)\n    Gradle Central Plugin Repository\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 34s\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "cmd": "./gradlew --init-script renovate-plugin.gradle renovate"
```

The `null` at the end of the stdout is me trying to print one of those environment variables.

**To Reproduce**

Any gradle project with a `settings.gradle.kts` file that contains a custom repository like

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            credentials {
                username = System.getenv("ARTIFACTORY_USERNAME")
                password = System.getenv("ARTIFACTORY_PASSWORD")
            }
            url = uri(System.getenv("ARTIFACTORY_BASE_URL"))
        }
    }
}
```

**Additional context**

/

**Comment by rarkins** [comment]
Should be fixed in v19.100.1 - please confirm

**Comment by gmariotti** [comment]
No, unfortunately doesn't seem to be fixed. I can see the cmd being called without using bash but still getting the same `null` at the end of the stdout when printing one of the environment variables

```
"cmd": "./gradlew --init-script renovate-plugin.gradle renovate",
"stdout": "Downloading https://services.gradle.org/distributions/gradle-5.6.4-bin.zip\n.........................................................................................
Unzipping /home/ubuntu/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4-bin.zip to /home/ubuntu/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux
Set executable permissions for: /home/ubuntu/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4/bin/gradle

Welcome to Gradle 5.6.4!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.4/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
null
"
```

**Comment by rarkins** [comment]
Was there a version of Renovate that ever worked in this scenario?

**Comment by gmariotti** [comment]
I'm not 100% sure about the version but at least until 19.91.2, I didn't have any problem

**Comment by gmariotti** [comment]
I'm not 100% sure about the version but at least until 19.91.2, I didn't have any problem

**Comment by rarkins** [comment]
Do you have [trustLevel](https://docs.renovatebot.com/self-hosted-configuration/#trustlevel) configured to "high"?

**Comment by gmariotti** [comment]
No, I don't have it in the `config.js`

```javascript
module.exports = {
    endpoint: 'https://git.naspersclassifieds.com/api/v4/',
    platform: 'gitlab',
    logFileLevel: 'warn',
    logLevel: 'info',
    logFile: './renovate.log',
    onboarding: true,
    extends: ['config:base', ":semanticCommitTypeAll(fix)"],
    prHourlyLimit: 0,
    assignees: [
        "plutus-ci"
    ],
    labels: [
        'renovate',
        'dependencies'
    ],
    hostRules: [
        {
            domainName: 'registry.naspersclassifieds.com',
            username: 'plutus-ci',
            password: process.env.RENOVATE_TOKEN
        },
        {
            domainName: 'docker.artifactory.olx.berlin',
            username: process.env.ARTIFACTORY_USERNAME,
            password: process.env.ARTIFACTORY_PASSWORD
        },
        {
            domainName: 'artifactory.olx.berlin',
            username: process.env.ARTIFACTORY_USERNAME,
            password: process.env.ARTIFACTORY_PASSWORD
        }
    ],
    onboardingConfig: {
        extends: ['config:base', ":semanticCommitTypeAll(fix)"],
        prHourlyLimit: 0,
        prConcurrentLimit: 0,
        masterIssue: true,
        masterIssueAutoclose: true,
        assignees: [
            "plutus-ci"
        ],
        labels: [
            'renovate',
            'dependencies'
        ]
    },
    repositories: [...]
}
```

**Comment by rarkins** [comment]
Can you try adding `trustLevel: 'high'` to that config? The purpose of this is to tell Renovate that it's OK to allow env variables to be read by the Gradle process. Otherwise we default to "low" and it only gets a select few env variables that we allow.

**Comment by gmariotti** [comment]
Works, thank you so much!!
