### ISSUE TITLE
Error when using local preset inside a packageRule

### ISSUE THREAD

**Issue by rdicroce** [renovatebot/renovate#7373]
**What Renovate type, platform and version are you using?**

Self-hosted Renovate 23.36.3
Self-hosted GitLab 13.3.6

**Describe the bug**

If a local preset is part of a packageRule, Renovate complains that the repository's configuration is invalid. The docs about presets say `preset configs may be as small as a partial package rule` which implies that this scenario should work.

**Relevant debug logs**

```
DEBUG: Repository config (repository=lapis/utilities/code-quality-typescript)
       "fileName": "renovate.json5",
       "config": {
         "extends": [
           "lapis/utilities/renovate-presets",
           "lapis/utilities/renovate-presets:dep_yarn_berry"
         ],
         "assignees": ["rcd"],
         "packageRules": [
           {
             "extends": [
               "lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)"
             ]
           },
           {
             "groupName": "typescript-eslint",
             "packagePatterns": ["^@typescript-eslint/"]
           }
         ]
       }
DEBUG: migrateAndValidate() (repository=lapis/utilities/code-quality-typescript)
DEBUG: No config migration necessary (repository=lapis/utilities/code-quality-typescript)
DEBUG: massaged config (repository=lapis/utilities/code-quality-typescript)
       "config": {
         "extends": [
           "lapis/utilities/renovate-presets",
           "lapis/utilities/renovate-presets:dep_yarn_berry"
         ],
         "assignees": ["rcd"],
         "packageRules": [
           {
             "extends": [
               "lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)"
             ]
           },
           {
             "groupName": "typescript-eslint",
             "packagePatterns": ["^@typescript-eslint/"]
           }
         ]
       }
TRACE: resolveConfigPresets (repository=lapis/utilities/code-quality-typescript)
       "config": {"extends": ["lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)"]},
       "existingPresets": []
TRACE: Resolving preset "lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)" (repository=lapis/utilities/code-quality-typescript)
TRACE: getPreset(lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)) (repository=lapis/utilities/code-quality-typescript)
DEBUG: Preset fetch error (repository=lapis/utilities/code-quality-typescript)
       "preset": "lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)",
       "err": {
         "message": "Missing platform config for local preset.",
         "stack": "Error: Missing platform config for local preset.\n    at Object.getPreset (/usr/lib/node_modules/renovate/dist/config/presets/local/index.js:30:15)\n    at getPreset (/usr/lib/node_modules/renovate/dist/config/presets/index.js:156:58)\n    at Object.resolveConfigPresets (/usr/lib/node_modules/renovate/dist/config/presets/index.js:214:43)\n    at Object.validateConfig (/usr/lib/node_modules/renovate/dist/config/validation.js:221:74)\n    at async Object.migrateAndValidate (/usr/lib/node_modules/renovate/dist/config/migrate-validate.js:43:39)\n    at async mergeRenovateConfig (/usr/lib/node_modules/renovate/dist/workers/repository/init/config.js:155:28)\n    at async Object.getRepoConfig (/usr/lib/node_modules/renovate/dist/workers/repository/init/config.js:217:14)\n    at async Object.initRepo (/usr/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/usr/lib/node_modules/renovate/dist/workers/repository/index.js:39:18)\n    at async Object.start (/usr/lib/node_modules/renovate/dist/workers/global/index.js:77:13)\n    at async /usr/lib/node_modules/renovate/dist/renovate.js:28:24"
       }
 INFO: Throwing preset error (repository=lapis/utilities/code-quality-typescript)
       "validationError": undefined
DEBUG: migrateAndValidate error (repository=lapis/utilities/code-quality-typescript)
       "config": {
         "extends": [
           "lapis/utilities/renovate-presets",
           "lapis/utilities/renovate-presets:dep_yarn_berry"
         ],
         "assignees": ["rcd"],
         "packageRules": [
           {
             "extends": [
               "lapis/utilities/renovate-presets:registry_nexus(npm,npm-public)"
             ]
           },
           {
             "groupName": "typescript-eslint",
             "packagePatterns": ["^@typescript-eslint/"]
           }
         ]
       }
 INFO: Repository has invalid config (repository=lapis/utilities/code-quality-typescript)
       "error": {}
```

**To Reproduce**

See the config in the debug log above. Judging from the code, any local preset inside any packageRule will cause this.

**Additional context**

I spent some time digging into Renovate's config validation code to understand why this doesn't work. The problem is around line 220 of lib/config/validation.ts. The validator wants to verify that the packageRule has a selector, and therefore needs to resolve any presets first. resolveConfigPresets expects the entire Renovate config to be passed as its second parameter. But because validateConfig calls itself recursively, it accidentally passes just the packageRule instead of the entire config.

To fix this, my first thought is to move the code in validateConfig to a new function validateConfigInternal that takes an additional topLevelConfig parameter. validateConfig just calls validateConfigInternal and passes the full config object as both config and topLevelConfig. Then when validateConfigInternal recurses and needs to call resolveConfigPresets, it passes the topLevelConfig as it should. If you agree with this approach, I can submit a PR.

**Comment by mfechner** [comment]
I had exactly the same problem and got it fixed by two changes.

- upgraded to 24.2.2
- install the npm dependencies with `npm ci --production` (used in a pipeline running on self-hosted gitlab)

Maybe this helps you too.

**Comment by viceice** [comment]
@rdicroce Do you still have this issue? i think this is now fixed on newer renovate?

**Comment by rdicroce** [comment]
@viceice Tested with 25.1.1 and it's still broken. I don't have time to work on this right now though. Maybe in a few weeks.

**Comment by rarkins** [comment]
This was not a use of extends we had originally intended. If the preset is an entire package rule then it could/should be created as a package rule itself and extended from the root extends.
