### ISSUE TITLE
Issue with the new release: Disallowed secret substitution

### ISSUE THREAD

**Issue by xoxys** [renovatebot/renovate#8066]
**What Renovate type, platform and version are you using?**

Self-hosted renovate

**Describe the bug**
```
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

File: config Error type: Disallowed secret substitution Message: The field semanticCommitType may not use secret substitution
```

The same config was working before 24.9.0

**Comment by viceice** [comment]
can you please share the relevant config parts?

**Comment by xoxys** [comment]
It's happening on all my repos. An example config looks like this:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base", "docker:enableMajor"],
  "ignorePresets": [":prHourlyLimit2"],
  "commitMessagePrefix": "Renovate:",
  "ansible": {
    "enabled": false
  },
  "ansible-galaxy": {
    "enabled": false
  },
  "regexManagers": [
    {
      "fileMatch": ["^(group_vars|services)/.*?$"],
      "matchStrings": [
        "# renovate: datasource=(?<datasource>\\S+) depName=(?<depName>\\S+)( versioning=(?<versioning>.*?))?\\n(?<roleName>\\S+?)_version: \"?(?<currentValue>.*?)\"?\\s"
      ]
    }
  ],
  "extractVersion": "^v?(?<version>.*)$",
  "packageRules": [
    {
      "packagePatterns": ["^drone"],
      "groupName": "Drone CI stack"
    },
    {
      "packagePatterns": ["^minio"],
      "versioning": "regex:^(RELEASE\\.)?(?<major>\\d{4})-(?<minor>\\d{2})-(?<patch>\\d{2})T\\S*?Z$",
      "extractVersion": "^RELEASE\\.(?<version>.*)$"
    }
  ]
}
```

Or do you mean server config?

**Comment by viceice** [comment]
we rolled back that feature as we found big bug

**Comment by Kage-Yami** [comment]
Is there a timeline for when this rollback will be applied to the GitLab CI template? I'm currently experiencing this issue over there across all of my enabled repositories (the last "failing" run being 55 minutes ago; Dec 19, 2020 12:11pm AEST).

Or, do I need to close off the generated issues for Renovate to actually try again on each repository?

**Comment by rarkins** [comment]
Sorry for that, I have fixed/upgraded the templates manually now

**Comment by Kage-Yami** [comment]
Thanks, I'm not seeing the errors in the runner logs now - though it looks like an update to 24.9.5 snuck in just before I kicked off the manual run, so it used that. 😅

**Comment by danez** [comment]
I'm still seeing this errors across all our repos. How do I fix this?
